apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: app
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: application
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: application
spec:
  type: ClusterIP
  ports:
    - name: application
      port: 8080
  selector:
    app: application